### PR TITLE
Retrained multiplex model

### LINKED ISSUE #465: Deepcell predicts huge and empty cells in data
**Describe the bug**
Deepcell is amazing when the image is full of cells. But where there are empty space, there will be empty (no nuclei and membrane) and huge (super big cell) prediction. 

**To Reproduce**
Multiplexed segmentation with the attached image.

**Screenshots**

99A7DAA6-CD4A-4D3A-B76F-BA564CAE7FF1

### PR DESCRIPTION
**Pull request by ngreenwald**
## What
Redid the TF2 training of current multiplex model. Visual inspection + metrics confirms the hallucinations are gone. Closes #465.

### CODE REVIEW

**Comment by ngreenwald** [comment]
Will, I uploaded it to the gcloud bucket. It looks like the public version is actually stored on AWS. Once you tar it and copy it over you should be able to update the MD5 here.

**Comment by willgraf** [comment]
@ngreenwald I've added the model to S3 and updated the hash.

Can you build this locally and make sure it doesn't hallucinate? If the model output of the application looks good then I will merge it in.

**Review by willgraf — COMMENTED** [review]
Can you test the new application to make sure it behaves as expected on the problematic data?

**Comment by ngreenwald** [comment]
yup sorry!!

**Comment by ngreenwald** [comment]
Good to go

**Pull request merged**
