### PR TITLE
Update MultiplexSegmentation model

### PR DESCRIPTION
**Pull request by msschwartz21**
Update the mesmer model from model-registry#15. I'll leave this PR as a draft until @ngreenwald has a chance to test post-processing parameters and determine if any changes are needed.

### CODE REVIEW

**Comment by ngreenwald** [comment]
Looks like the URL is private
image

**Comment by msschwartz21** [comment]
Good catch! Thank you for checking the link! It should be good accessible now.

**Comment by msschwartz21** [comment]
It looks like the tar file didn't grab all of the correct files for the saved model when I made it. I'll need to wait until madrox is back online, but I'll try taring it again and see if I can correct the error.

**Review by ngreenwald — APPROVED** [review]
Looks good. Just tried it out and everything looks great. I'm going to hold off on seeing if the post-processing params need to be tuned until the next version is merged in

**Pull request merged**
